const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

// Paths
const rootEnvPath = path.join(__dirname, '../../.env');
const backendEnvPath = path.join(__dirname, '../../backend/.env');
// Target: frontend/js/env.js (relative to backend/scripts/)
const frontendEnvPath = path.join(__dirname, '../../frontend/js/env.js');

console.log('🔄 Syncing Environment Variables...');

// Load Env Files
const rootConfig = dotenv.config({ path: rootEnvPath }).parsed || {};
const backendConfig = dotenv.config({ path: backendEnvPath }).parsed || {};

// Extract Values (with defaults)
const WHATSAPP_PHONE = rootConfig.WHATSAPP_PHONE || rootConfig.whatsapp_phone || '201227624726';
const PORT = backendConfig.PORT || 5001;

// Template for js/env.js
const fileContent = `/**
 * Environment Configuration
 * Auto-generated by backend/scripts/sync-env.js
 * Do not edit this file directly. Update .env files instead.
 */

const ENV = {
    // WhatsApp Configuration (from root .env)
    WHATSAPP_PHONE: '${WHATSAPP_PHONE}',

    // Backend API (derived from backend .env)
    API_URL: 'http://localhost:${PORT}/api'
};

// Make ENV available globally
window.ENV = ENV;
`;

// Write File
try {
    // Ensure directory exists
    const dir = path.dirname(frontendEnvPath);
    if (!fs.existsSync(dir)){
        fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(frontendEnvPath, fileContent);
    console.log(`✅ Frontend config updated at: ${frontendEnvPath}`);
    console.log(`   - WhatsApp: ${WHATSAPP_PHONE}`);
    console.log(`   - API URL: http://localhost:${PORT}/api`);
} catch (error) {
    console.error('❌ Failed to update frontend config:', error);
    process.exit(1);
}
