/**
 * Environment Configuration
 * Auto-generated by backend/scripts/sync-env.js
 * Do not edit this file directly. Update .env files instead.
 */

const ENV = {
    // WhatsApp Configuration (from root .env)
    WHATSAPP_PHONE: '201149219332',

    // Backend API (derived from backend .env)
    API_URL: '/api'
};

// Make ENV available globally
window.ENV = ENV;
